//! report.rs — Formatter emitting SUPPLY-CHAIN.md, SVG badge, and JSON.

use crate::score::ScoreReport;

pub fn emit_markdown(report: &ScoreReport) -> String {
    let mut out = String::new();
    out.push_str("# SUPPLY-CHAIN.md — Supply-Chain Health Audit\n\n");
    out.push_str("> Generated by [Vigil](https://studio2201.com/vigil) · studio2201\n\n");
    out.push_str(&format!(
        "**Target Manifest**: `{}`  \n**Total Dependencies**: {}  \n**Average Risk Score**: {:.1}/100\n\n",
        report.manifest_path, report.total_deps, report.average_score
    ));

    out.push_str("### Risk Breakdown\n\n");
    out.push_str("| Risk Level | Count |\n| :--- | :--- |\n");
    out.push_str(&format!("| 🔴 Critical | {} |\n", report.critical_count));
    out.push_str(&format!("| 🟠 High | {} |\n", report.high_count));
    out.push_str(&format!("| 🟡 Medium | {} |\n", report.medium_count));
    out.push_str(&format!("| 🟢 Low | {} |\n\n", report.low_count));

    out.push_str("### Dependency Detail\n\n");
    out.push_str("| Package | Version | Dormancy | Annual Velocity | Risk Score | Level |\n");
    out.push_str("| :--- | :--- | :--- | :--- | :--- | :--- |\n");

    for dep in &report.entries {
        out.push_str(&format!(
            "| `{}` | {} | {}d | {:.1} commits/yr | {:.1} | {} |\n",
            dep.name, dep.version, dep.days_dormant, dep.commit_velocity, dep.risk_score, dep.risk_level
        ));
    }

    out
}

pub fn emit_json(report: &ScoreReport) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(&format!("  \"manifest_path\": \"{}\",\n", report.manifest_path));
    out.push_str(&format!("  \"total_dependencies\": {},\n", report.total_deps));
    out.push_str(&format!("  \"average_score\": {:.2},\n", report.average_score));
    out.push_str(&format!("  \"critical_count\": {},\n", report.critical_count));
    out.push_str(&format!("  \"high_count\": {},\n", report.high_count));
    out.push_str(&format!("  \"medium_count\": {},\n", report.medium_count));
    out.push_str(&format!("  \"low_count\": {},\n", report.low_count));
    out.push_str("  \"dependencies\": [\n");

    for (i, dep) in report.entries.iter().enumerate() {
        let comma = if i + 1 < report.entries.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{\"name\": \"{}\", \"version\": \"{}\", \"is_dev\": {}, \"days_dormant\": {}, \"risk_score\": {:.2}, \"level\": \"{}\"}}{}\n",
            dep.name, dep.version, dep.is_dev, dep.days_dormant, dep.risk_score, dep.risk_level, comma
        ));
    }

    out.push_str("  ]\n");
    out.push_str("}\n");
    out
}

pub fn emit_badge_svg(score: f32) -> String {
    let color = if score < 25.0 {
        "#2f6f5e" // Green
    } else if score < 50.0 {
        "#d48806" // Yellow
    } else if score < 75.0 {
        "#d4380d" // Orange
    } else {
        "#cf1322" // Red
    };

    let status = if score < 25.0 {
        "healthy"
    } else if score < 50.0 {
        "moderate"
    } else if score < 75.0 {
        "dormant"
    } else {
        "critical"
    };

    format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"124\" height=\"20\">\
          <linearGradient id=\"b\" x2=\"0\" y2=\"100%\">\
            <stop offset=\"0\" stop-color=\"#bbb\" stop-opacity=\".1\"/>\
            <stop offset=\"1\" stop-opacity=\".1\"/>\
          </linearGradient>\
          <clipPath id=\"a\">\
            <rect width=\"124\" height=\"20\" rx=\"3\" fill=\"#fff\"/>\
          </clipPath>\
          <g clip-path=\"url(#a)\">\
            <path fill=\"#555\" d=\"M0 0h44v20H0z\"/>\
            <path fill=\"{}\" d=\"M44 0h80v20H44z\"/>\
            <path fill=\"url(#b)\" d=\"M0 0h124v20H0z\"/>\
          </g>\
          <g fill=\"#fff\" text-anchor=\"middle\" font-family=\"DejaVu Sans,Verdana,sans-serif\" font-size=\"11\">\
            <text x=\"22\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">vigil</text>\
            <text x=\"22\" y=\"14\">vigil</text>\
            <text x=\"84\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">{}</text>\
            <text x=\"84\" y=\"14\">{}</text>\
          </g>\
        </svg>",
        color, status, status
    )
}
